#!/usr/bin/env python
"""Get a list of all sensors in a system."""
import asyncio
import logging
import sys

from simplipy import get_api
from simplipy.errors import PendingAuthorizationError


async def main() -> None:
    """Run!"""
    logging.basicConfig(level=logging.INFO)
    while True:
        try:
            email = input("What is your SimpliSafe email address? ")
            password = input("What is your SimpliSafe email password? ")
            client_id = input("(optional) What is your SimpliSafe client ID? ")

            await get_api(
                email, password, client_id=client_id or None
            )
        except PendingAuthorizationError as err:
            print(str(err))
            sys.exit(0)
        except KeyboardInterrupt:
            sys.exit(0)


asyncio.run(main())
